site_name: Jetson Docs
site_url: https://jetsondocs.federicolanzani.com
site_author: Federico Lanzani
site_description: >-
  NVIDIA Jetson independent documentation.

# Repository
repo_name: lanzani/jetsondocs
repo_url: https://github.com/lanzani/jetsondocs

theme:
  name: material
  language: en

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: green
      accent: blue

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: blue

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lanzani
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/FederLanzani
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lanzani/

nav:
  - Home: index.md
  - Getting started:
      - getting-started/index.md
      - Board configuration:
          - Jetson Nano 2GB/4GB: getting-started/jetson-nano.md
      - What is ...?:
          - Gstreamer: getting-started/what-is/gstreamer.md
          - Deepstream: getting-started/what-is/deepstream.md

  - Libraries on jetson:
      - building-on-jetson/index.md
      - Machine Learning:
          - building-on-jetson/tensorflow.md
      - Computer Vision:
          - building-on-jetson/opencv.md
          - building-on-jetson/mediapipe.md
  - Docker:
      - docker/index.md
      - Base NVIDIA images: docker/base.md
      - OpenCV: docker/opencv.md
      - Mediapipe: docker/mediapipe.md
